---
name: Catalyst-View-TT-FunctionGenerator
version: 0.01
author: ~
abstract: Generate functions from ... to be used from a TT view
license: perl
requires:
  Catalyst: 5.61
  Catalyst::View::TT: 0.22
  perl: 5.8.1
provides:
  Catalyst::View::TT::FunctionGenerator:
    file: lib/Catalyst/View/TT/FunctionGenerator.pm
    version: 0.01
generated_by: Module::Build version 0.2611
